//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmpDet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CmpDet()
        {
            this.CmpDet1 = new HashSet<CmpDet>();
        }
    
        public string CmpCd { get; set; }
        public string CmpDesc { get; set; }
        public string CmpDispNm { get; set; }
        public Nullable<long> CmpCmpFk { get; set; }
        public long CmpPk { get; set; }
        public Nullable<System.Guid> CmpRowid { get; set; }
        public string CmpCreatedBy { get; set; }
        public System.DateTime CmpCreatedDt { get; set; }
        public string CmpModifiedBy { get; set; }
        public System.DateTime CmpModifiedDt { get; set; }
        public string CmpDelFlg { get; set; }
        public byte CmpDelId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CmpDet> CmpDet1 { get; set; }
        public virtual CmpDet CmpDet2 { get; set; }
    }
}
