//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SampleDB_EFEntities : DbContext
    {
        public SampleDB_EFEntities()
            : base("name=SampleDB_EFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<CmpDet> CmpDets { get; set; }
        public virtual DbSet<ProFaCurConvConfig> ProFaCurConvConfigs { get; set; }
        public virtual DbSet<ProFaCurdef> ProFaCurdefs { get; set; }
        public virtual DbSet<ProFaMgTimeZone> ProFaMgTimeZones { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<cmpma> cmpmas { get; set; }
        public virtual DbSet<tmp> tmps { get; set; }
        public virtual DbSet<tmp1> tmp1 { get; set; }
        public virtual DbSet<TmpSvsInterComp> TmpSvsInterComps { get; set; }
        public virtual DbSet<UniqCustCode> UniqCustCodes { get; set; }
    }
}
