//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProFaCurConvConfig
    {
        public decimal CrvLocFk { get; set; }
        public decimal CrvBasCurFk { get; set; }
        public decimal CrvConCurFk { get; set; }
        public decimal CrvByRt { get; set; }
        public decimal CrvSelRt { get; set; }
        public System.DateTime CrvEffFrm { get; set; }
        public Nullable<System.DateTime> CrvEffTo { get; set; }
        public decimal CrvConvVal { get; set; }
        public string CrvCutOffTm { get; set; }
        public Nullable<decimal> CrvFcr1 { get; set; }
        public Nullable<decimal> CrvFcr2 { get; set; }
        public Nullable<decimal> CrvFcr3 { get; set; }
        public int CrvPk { get; set; }
        public System.Guid CrvRowid { get; set; }
        public string CrvCreatedBy { get; set; }
        public System.DateTime CrvCreatedDt { get; set; }
        public string CrvModifiedBy { get; set; }
        public System.DateTime CrvModifiedDt { get; set; }
        public string CrvDelFlg { get; set; }
        public Nullable<byte> CrvDelId { get; set; }
    }
}
