//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProFaMgTimeZone
    {
        public string TZnCd { get; set; }
        public string TZnDesc { get; set; }
        public string TZnDispNm { get; set; }
        public string TZnoffset { get; set; }
        public string TZnoffsetmin { get; set; }
        public int TZnPk { get; set; }
        public Nullable<System.Guid> TZnRowid { get; set; }
        public string TZnCreatedBy { get; set; }
        public Nullable<System.DateTime> TZnCreatedDt { get; set; }
        public string TZnModifiedBy { get; set; }
        public Nullable<System.DateTime> TZnModifiedDt { get; set; }
        public string TZnDelFlg { get; set; }
        public Nullable<byte> TZnDelId { get; set; }
    }
}
