//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProFaMgGeneral
    {
        public int GnmTyp { get; set; }
        public Nullable<byte> GnmEntry { get; set; }
        public string GnmCd { get; set; }
        public string GnmDesc { get; set; }
        public string GnmDispNm { get; set; }
        public Nullable<byte> GnmIsManual { get; set; }
        public string GnmSecCur { get; set; }
        public Nullable<short> GnmCurEql { get; set; }
        public string GnmSubCd { get; set; }
        public Nullable<int> GnmIncGI { get; set; }
        public Nullable<int> GnmModTyp { get; set; }
        public Nullable<int> GnmBillPass { get; set; }
        public Nullable<int> GnmValnTyp { get; set; }
        public Nullable<int> GnmCusFld { get; set; }
        public Nullable<int> GnmCurdigit { get; set; }
        public Nullable<int> GnmQtydigit { get; set; }
        public Nullable<int> GnmScrTyp { get; set; }
        public Nullable<int> GnmEntStg { get; set; }
        public long GnmPK { get; set; }
        public System.Guid GnmRowid { get; set; }
        public string GnmCreatedBy { get; set; }
        public System.DateTime GnmCreatedDt { get; set; }
        public string GnmModifiedBy { get; set; }
        public System.DateTime GnmModifiedDt { get; set; }
        public string GnmDelFlg { get; set; }
        public byte GnmDelId { get; set; }
        public Nullable<long> GnmPhFk { get; set; }
        public Nullable<long> GnmRelVchTypFk { get; set; }
        public Nullable<long> GnmFrmUmpFk { get; set; }
        public Nullable<long> GnmToUmpFk { get; set; }
        public Nullable<long> GnmPimFk { get; set; }
        public Nullable<long> GnmCcFk { get; set; }
        public Nullable<byte> GnmIsValdInc { get; set; }
        public Nullable<byte> GnmSusPen { get; set; }
    
           }
}
