//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace CurApi.Models
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class ProFaCurdef
//    {
//        public long CurPK { get; set; }
//        public string CurCd { get; set; }
//        public string CurDesc { get; set; }
//        public string CurDispNm { get; set; }
//        public string CurSecCur { get; set; }
//        public System.Guid CurRowid { get; set; }
//        public string CurCreatedBy { get; set; }
//        public System.DateTime CurCreatedDt { get; set; }
//        public string CurModifiedBy { get; set; }
//        public System.DateTime CurModifiedDt { get; set; }
//        public string CurDelFlg { get; set; }
//        public Nullable<byte> CurDelId { get; set; }
//    }
//}
