//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp
    {
        public string CmpCd { get; set; }
        public string CmpDesc { get; set; }
        public string CmpDispNm { get; set; }
        public Nullable<long> CmpCmpFk { get; set; }
        public long CmpPk { get; set; }
        public Nullable<System.Guid> CmpRowid { get; set; }
        public string CmpCreatedBy { get; set; }
        public System.DateTime CmpCreatedDt { get; set; }
        public string CmpModifiedBy { get; set; }
        public System.DateTime CmpModifiedDt { get; set; }
        public string CmpDelFlg { get; set; }
        public byte CmpDelId { get; set; }
    }
}
