//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniqCustCode
    {
        public string CompShrtDescr { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }
        public string CorrAddress { get; set; }
        public string City { get; set; }
        public Nullable<decimal> PinCode { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string StatFlag { get; set; }
        public string AadharNo { get; set; }
        public string PAN { get; set; }
        public string RationCardNo { get; set; }
        public string DrivingLicenseNo { get; set; }
        public string PassportNo { get; set; }
        public string VoterID { get; set; }
        public string UnitName { get; set; }
        public string StateName { get; set; }
        public string Key1 { get; set; }
        public string Name { get; set; }
        public string Addr { get; set; }
        public Nullable<byte> Dumy { get; set; }
        public string Processed { get; set; }
        public int pkid { get; set; }
        public string AadharNoMod { get; set; }
        public string PANMod { get; set; }
        public string RationCardNoMod { get; set; }
        public string DrivingLicenseNoMod { get; set; }
        public string PassportNoMod { get; set; }
        public string VoterIDMod { get; set; }
        public Nullable<bool> IsLive { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
        public Nullable<System.DateTime> CustLnDt { get; set; }
        public string TmpFld { get; set; }
        public Nullable<int> LnCnt { get; set; }
        public Nullable<int> IsPrimary { get; set; }
        public Nullable<int> LnCnt2 { get; set; }
        public string grpcdchar { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public string LnStat { get; set; }
    }
}
